import json,hashlib,base64,shutil,datetime
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
root=Path(__file__).resolve().parents[1];current=root/'outputs/v42_path_study/iteration_09_cloak_counterwing';delivery=root/'outputs/v42_delivery_checkpoint';delivery.mkdir(exist_ok=True);(delivery/'textures').mkdir(exist_ok=True);(delivery/'evidence').mkdir(exist_ok=True)
modelpath=current/'projects_noctveil_v42_timed_sweep_review.bbmodel';model=json.loads(modelpath.read_text());source=json.loads((root/'outputs/v32/projects_noctveil_v32_idle_storage.bbmodel').read_text());assert all(model[k]==source[k] for k in ['elements','outliner','textures']) and model['animations'][1:]==source['animations']
native=json.loads((root/'outputs/v42_path_study/iteration_07/v42_native_sparse_verification.json').read_text());mid=json.loads((root/'outputs/v42_path_study/iteration_07/v42_clear_midpoint_verification.json').read_text());joint=json.loads((root/'outputs/v42_path_study/iteration_07/v42_midpoint_contact_classification.json').read_text());counter=json.loads((current/'v42_counterwing_evidence.json').read_text());whole=json.loads((current/'v42_self_surface_crossing_audit.json').read_text());lib=json.loads((root/'work/PARENT_HANDOFF_V42_NATIVE_PNG_UPDATED.json').read_text());now=datetime.datetime.now(datetime.timezone.utc).isoformat()
font=lambda n:ImageFont.truetype('C:/Windows/Fonts/segoeui.ttf',n);board=Image.new('RGB',(1000,820),(31,28,35));d=ImageDraw.Draw(board);d.text((14,12),'NOCTVEIL v42 / CURRENT GUI-FREE SWEEP REVIEW',font=font(22),fill='white');d.text((14,45),'iteration_09 / original shape, UV, pixel atlases and3 original clips preserved',font=font(16),fill=(194,204,218));d.text((14,70),'Software preview: native shading equivalence NOT established. No game connection or art pass.',font=font(15),fill=(242,184,124))
sheet=Image.open(current/'noctveil_v42_short_sweep_all_frames.png');selected=[0,9,11,13,16,19];labels=['OUTSIDE LOAD /0.00s','APPROACH /0.75s','ENTRY /0.92s','CROSS /1.08s','EXIT /1.33s','EXIT HOLD /1.58s']
for n,(i,label) in enumerate(zip(selected,labels)):
 x=(i%5)*320;y=(i//5)*265+25;frame=sheet.crop((x,y,x+320,y+240));dx=14+(n%3)*328;dy=132+(n//3)*285;d.text((dx,dy-23),label,font=font(14),fill='white');board.paste(frame,(dx,dy))
d.text((14,718),'Normal320x240 inspection frames / fixed opponent guide / closed opposite wing',font=font(16),fill=(189,199,214));d.text((14,746),'Limits: unresolved seam contacts; whole-solid/continuous collision, idle return and final timing unverified.',font=font(15),fill=(189,199,214));d.text((14,774),'MatE quality equivalence has not been established. Reference pixels are not included.',font=font(15),fill=(189,199,214));review=current/'noctveil_v42_current_review.png';board.save(review)
copies=[(modelpath,delivery/'ProjectS_Noctveil_v42_review.bbmodel'),(review,delivery/'ProjectS_Noctveil_v42_current_review.png'),(root/'outputs/v42_path_study/iteration_07/noctveil_v42_native_pose_review.png',delivery/'ProjectS_Noctveil_v42_native_review.png'),(current/'noctveil_v42_short_sweep_review.gif',delivery/'ProjectS_Noctveil_v42_sweep_preview.gif')]
for a,b in copies:shutil.copyfile(a,b)
for i,t in enumerate(model['textures']):
 path=delivery/'textures'/('noctveil_mantle.png' if i==0 else 'noctveil_anatomy.png');path.write_bytes(base64.b64decode(t['source'].split(',',1)[1]));assert Image.open(path).size==(512,512)
gui={'editing':'GUI-free direct bbmodel JSON authoring; no geometry/UV/material changes','numeric_qa':'GUI-free bone/world vertices, contact brackets, ground, leg reach, shared edges, mesh surface crossings','ordinary_motion_preview':'Existing mesh_preview.py320x24025 frames,2.05s; GUI-free, no new renderer','proven_parity':{'current_iteration_07_native_poses':4,'max_vertex_difference_units':max(r['maximum_native_software_vertex_error'] for r in native['sparse_samples']),'native_textures_errors':0,'scope':'Geometry/world transforms only, not image pixel/shading equivalence.'},'native_qa_still_required':'Final Blockbench material/UV/backface/pose presentation and actual animation-player behavior where not yet verified. Keep to short necessary checks after the user playtest; no automatic frequent GUI launches.','not_verified':'Renderer image parity, actual Minecraft/ModelEngine behavior, final timing/idle-return/damage, MatE aesthetic equivalence','own_Blockbench_closed':True,'native_short_motion_script_not_run_due_GUI_load_preference':True,'Minecraft_window_or_input_touched':False}
limits={'at_utc':now,'stage':'Concept > real native model > partial static/path/motion QA > game not connected','current_model_sha256':counter['sha256'],'native_review_candidate':'iteration_07','GUI_free_current_candidate':'iteration_09_cloak_counterwing','geometry_uv_textures_original3_clips_exact':True,'closed_counterwing_source':'closed_idle_breath_v32 at0;16 existing left-wing bones only','midpoint_checks_prior_strike_path':mid['summary'],'residual_shared_seam_contacts':{'observations':54,'adjacent_faces':[15,16],'shared_edge':[14,12],'maximum_distance_from_shared_edge':joint['maximum_distance_from_shared_edge'],'interpretation':'Very small shared-edge contacts from key interpolation; segment length is not penetration depth. Not declared a full self-collision pass.'},'current_timed_ground_minimum65_samples':counter['minimum_all_mesh_y_65_timed_samples'],'current_full_body_surface_samples':len(whole['samples']),'current_new_wing_nonadjacent_crossing_pairs':whole['new_wing_nonadjacent_crossing_pairs'],'full_body_self_collision_pass':False,'continuous_time_solid_collision_proof':False,'idle_return_or_state_transition_validated':False,'final_timing_or_game_hitbox_calibrated':False,'MatE_quality_reference_pixels_seen_in_this_worker':False,'art_pass':False,'game_connected':False,'gui_capability':gui}
(delivery/'evidence/v42_stage_and_validation.json').write_text(json.dumps(limits,indent=2)+'\n',encoding='utf8')
readme='Noctveil V42 制作・検証用の別候補\n\n承認済み原本の形・UV・テクスチャ・既存3アニメは保持しています。新しい払いレビューを加えた候補です。ゲームへは未接続です。\n\n最新モデルとGUIなしプレビューはiteration_09、Blockbench実表示レビューはiteration_07です。ソフトウェアの陰影はBlockbenchと完全一致を保証していません。\n\n2.05秒の映像は予備動作から反対側への払いと停止までです。待機への復帰、状態遷移、最終タイミング、当たり判定・ダメージ・ゲームバランスは未検証です。\n\n頭と頭冠への交差、地面貫通は保存した検査点で解消しています。膜の共有端に中間姿勢の小さな交差が残ります。全身自己衝突・連続時間の衝突・MatE品質について合格とは扱っていません。\n\nReference作品の画像・動画は同梱しません。\n'
(delivery/'README.txt').write_text(readme,encoding='utf8')
source_files=['work/noctveil_v42_pose_tools.py','work/build_v42_clear_sweep.py','work/build_v42_timed_review.py','work/build_v42_closed_counterwing.py','work/render_v42_short_gui_free.py','work/inspect_v42_self_collision.py','work/inspect_v42_head_clear_body.py','work/verify_v42_clear_midpoints.py','work/classify_v42_membrane_midpoint_contacts.py','work/verify_native_v42.py','work/native_v42_arc_static.cjs','work/compose_v42_native_review.py','work/refine_v42_contact_brackets.py','work/save_v42_push_checkpoint.py']
def entry(path,role):data=path.read_bytes();return {'local_path':str(path),'workspace_relative_path':str(path.relative_to(root)).replace('\\','/'),'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest(),'role':role}
manifest={'at_utc':now,'workspace':str(root),'is_git_repository':False,'repo':None,'branch':None,'commit':None,'push_executor':'Delegated parent task01a1022f-884a-7190-92a6-e08bb1289093 owns commit/push; this worker never writes the existing repo or runs git push.','delivery_files':[entry(p,'current_review_artifact') for p in sorted(delivery.rglob('*')) if p.is_file()],'owned_editing_sources':[entry(root/p,'authoring_source_archive') for p in source_files],'source_dependencies':'These editing scripts use the existing Noctveil authoring workspace (v32 protected input and v35/v40/v41 helper/topology files). Delivered bbmodel is self-contained with embedded textures; those scripts are not a standalone runtime or game integration.','exclude':['work/references/**: original reference images/GIF/MP4','work/blockbench-profile-*/** and browser profiles/cookies','Library helpers, raw transfer responses, Library identity receipts and signed URLs','all portable tools/runtime binaries and process logs','superseded trial models/large motion renders/ZIPs unless separately requested','all unmodified protected originals and unrelated other-task files'],'originals_modified':False,'main_merge_force_push_deploy_or_public_setting_changed':False,'limits':limits}
(root/'work/PARENT_HANDOFF_V42_PUSH_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf8')
handoff={'at_utc':now,'saved_model':str(modelpath.relative_to(root)),'model_sha256':counter['sha256'],'delivery_dir':str(delivery),'push_manifest':'work/PARENT_HANDOFF_V42_PUSH_MANIFEST.json','native_png_library':{'library_file_id':lib['library_file_id'],'file_id':lib['file_id'],'version':lib['current_version_number'],'name':lib['file_name'],'actual_candidate':'iteration_07'},'current_gui_free_review_png':str(review.relative_to(root)),'current_motion_gif':str((current/'noctveil_v42_short_sweep_review.gif').relative_to(root)),'gui_capability':gui,'latest_limits':limits,'next':'Continue GUI-free: improve arm/claw readability and anticipation/return path, resolve/characterize shared seam contacts, compare actual MatE pixels once legitimately supplied. Sparse native final QA only when necessary; no Minecraft input.'}
(root/'work/PARENT_HANDOFF_V42_GUI_AND_PUSH_CHECKPOINT.json').write_text(json.dumps(handoff,indent=2)+'\n',encoding='utf8');print(json.dumps({'delivery_files':len(manifest['delivery_files']),'owned_sources':len(source_files),'bytes':sum(p['bytes'] for p in manifest['delivery_files']),'model_sha256':counter['sha256'],'native_png_library':handoff['native_png_library'],'manifest':manifest['workspace']+'/work/PARENT_HANDOFF_V42_PUSH_MANIFEST.json'}))
