from pathlib import Path
ROOT=Path(__file__).resolve().parent
p=ROOT/'preview/viewer.html'
p.write_text('''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>氷の庭 — 接触12</title><style>body{font:16px system-ui;background:#14202c;color:#dfedf5;margin:24px}main{max-width:1280px;margin:auto}button{padding:10px;margin:4px;background:#284454;color:white;border:1px solid #617f90;border-radius:4px}img{display:block;max-width:100%;image-rendering:pixelated;margin:16px 0}input{width:min(640px,100%)}small{color:#a6bfcd}</style><main><h1>氷の庭 — 接触12</h1><p>細い左右の翼から、片側が先に割れ、厚い破断面が止まってから落ちる接触へ。</p><p><small>11cの主結晶・床を保護した独立表示試作。ゲーム操作・音・実機の手触りは未確認です。</small></p><div id="buttons"></div><img id="image" alt="接触比較"><label>接触をコマ送り <input id="scrub" type="range" min="0" max="31" value="0"></label><p id="time"></p></main><script>const files=[['11c → 12 通常速度','11c-to-12-contact.gif'],['12 接触 通常速度','contact-12.gif'],['接触の全段階','contact-phases.png'],['斜め','oblique.png'],['近距離','near.png'],['明るい床','light.png'],['暗い床','dark.png']];const im=document.getElementById('image');for(const [title,file] of files){const b=document.createElement('button');b.textContent=title;b.dataset.file=file;b.onclick=()=>{im.src=file;document.getElementById('time').textContent=title};document.getElementById('buttons').append(b)}const slider=document.getElementById('scrub');slider.oninput=()=>{im.src='frames/'+String(slider.value).padStart(3,'0')+'.png';document.getElementById('time').textContent='接触 '+(Number(slider.value)*.025-.22).toFixed(3)+' 秒'};im.src=files[0][1];</script></html>''',encoding='utf-8')
s=(ROOT.parent/'ice-garden-ridge-11/playback11.mjs').read_text()
s=s.replace("[['prototype-11.gif',[.08,.66,.86,1.10,1.55,2.26,3.26,3.86]],['ending-10-to-11.gif',[.06,.22,.58,.98,1.14,1.42,1.90]]]", "[['contact-12.gif',[.19,.25,.32,.40,.50,.60,.72]],['11c-to-12-contact.gif',[.19,.32,.60,.99,1.12,1.40,1.52]]]")
s=s.replace('width:800px;height:478px','width:640px;height:388px').replace('loaded.w!==800||loaded.h!==478','loaded.w!==640||loaded.h!==388').replace('[0,20,27,56,88,100,111,124]','[0,8,10,12,15,20,26,31]').replace('im.naturalWidth===800','im.naturalWidth===640')
(ROOT/'playback12.mjs').write_text(s)
print('viewer + installed-browser probe saved')
