"""Separate research handoff; do not rewrite push actor's v42 bundle."""
import json,hashlib
from pathlib import Path
root=Path(__file__).resolve().parents[1];out=root/'outputs/v43_gesture_study'
e=json.loads((out/'v43_three_pose_evidence.json').read_text());a=json.loads((out/'v43_three_pose_full_body_surface_audit.json').read_text());lib=json.loads((root/'work/PARENT_HANDOFF_V43_COMPARISON_LIBRARY.json').read_text())
assert hashlib.sha256((root/'outputs/v32/projects_noctveil_v32_idle_storage.bbmodel').read_bytes()).hexdigest()=='c0f243de33b471e201052dc6fb66d4372356e56aa645f669ce97ce4016aa0878'
assert hashlib.sha256((root/'outputs/v42_path_study/iteration_09_cloak_counterwing/projects_noctveil_v42_timed_sweep_review.bbmodel').read_bytes()).hexdigest()=='8809b24da17f3ef7b8e8aeb8d8ad52c0da842ba14335e2d4f907f678bcb25e98'
handoff={'current_motion_candidate':'v42 iteration09; full whole-gesture verdict FIX-FIRST','latest_motion_gif':{'library_file_id':'libfile_ae6b86115d4c8191aed35fedf3463f94','file_id':'file_0000000057108209a5adc2db2b35d492','version':0,'duration_ms':2050,'frames':25},'research_candidate':e['model'],'research_model_sha256':e['sha256'],'comparison_library':lib,'research_scope':'Three separate static study clips only. Original3 source clips exact. Native07 verification does not cover v43. Current textures/UV/geometry/hierarchy exact original. No full motion or idle return claim.','review_verdict':'FIX-FIRST: closed-wing load removes initial wide spread; contact hand direction+forward wrist and chest drop improve oblique exposure, but hand remains small and front contact not clearly readable; oblique exit hand still0 visiblepixels. Counts diagnostic only, no artistic pass.','current09_parent_rejection':e['previous_iteration09_review'],'finite_checks':{'head_crown_crossings_three_poses':[len(r['head_and_crown_crossings']) for r in e['selected_poses']],'minimum_all_y':min(r['minimum_all_y'] for r in e['selected_poses']),'contact_target':'At selected contact, hook overlaps fixed target, membrane_panel05 also overlaps. This is a late contact pose, not proof of hook-first timing. Palm/radius overlap false. Target unchangedX[-5,5]Y[0,18]Z[-32,-28].','new_nonadjacent_wing_crossings':[(h['pose'],h['a'],h['b']) for h in a['new_nonadjacent_wing_crossings']],'full_body_pass':False},'remaining':['Improve exit hand exposure and front crossing silhouette without changing protected shape.','Rebuild connected wrist arc and body-drive timing; prove observed hook-before-membrane order on actual saved interpolation.','Construct closed idle entry + non-striking recovery and foot return; not simple backwards replay.','Check full-body interactions including opposite wing through real interpolation and ordinary front/oblique motion.','Native final current model check only when needed; no old-version native pass carryover.'],'next_authorized_step':'Pose-only exit routing and wrist/hand presentation work continues from this separate checkpoint. Shape edits are not authorized and are not yet shown necessary; no geometry/material changes requested.','gui_runtime_used':False,'minecraft_windows_or_input_touched':False,'game_connected':False,'whole_body_gesture_pass':False,'art_pass':False,'is_git_repository':False,'push_executor':'Parent task01a1022f-884a-7190-92a6-e08bb1289093; no worker Git mutation/push. Existing v42 delivery/manifest untouched.'}
(root/'work/PARENT_HANDOFF_V43_GESTURE_RESEARCH.json').write_text(json.dumps(handoff,indent=2)+'\n',encoding='utf8')
paths=[out/'projects_noctveil_v43_three_pose_study.bbmodel',out/'noctveil_v43_three_pose_comparison.png',out/'v43_three_pose_evidence.json',out/'v43_three_pose_full_body_surface_audit.json',out/'v43_three_gesture_probe.json',out/'v43_hand_lead_scan.json']+[root/'work'/n for n in ['probe_v43_three_gestures.py','probe_v43_hand_leads.py','save_v43_three_pose_review.py','audit_v43_three_pose_body.py','save_v43_research_checkpoint.py']]
manifest={'workspace':str(root),'branch':None,'commit':None,'is_git_repository':False,'parent_push_executor':handoff['push_executor'],'files':[{'local_path':str(p),'workspace_relative_path':p.relative_to(root).as_posix(),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in paths],'exclusions':'Reference originals, Library receipt/internal metadata, runtimes/profiles/cookies, unchanged v42 delivery and unapproved historical models not added. Authoring sources depend on existing Noctveil workspace helpers; delivered bbmodel self-contained.'}
(root/'work/PARENT_HANDOFF_V43_PUSH_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf8')
print(json.dumps({'sha256':e['sha256'],'files':len(paths),'verdict':'FIX-FIRST','library_file_id':lib['library_file_id']}))
