// Read-only protocol/resourcepack smoke against the owned local playground server. No gameplay input.
const fs=require('fs'),net=require('net'),JSZip=require('jszip'),sharp=require('sharp');
function variable(n){const out=[];n>>>=0;do{let b=n&127;n>>>=7;if(n)b|=128;out.push(b)}while(n);return Buffer.from(out)}
function str(s){let b=Buffer.from(s);return Buffer.concat([variable(b.length),b])}
function frame(b){return Buffer.concat([variable(b.length),b])}
function read(b,offset=0){let value=0;for(let n=0;n<5;n++){if(offset+n>=b.length)return null;let v=b[offset+n];value|=(v&127)<<(7*n);if(!(v&128))return {value:value>>>0,bytes:n+1}}throw Error('Malformed VarInt')}
async function status(port){return new Promise((resolve,reject)=>{const c=net.connect({host:'127.0.0.1',port});let b=Buffer.alloc(0);c.setTimeout(5000,()=>c.destroy(Error('Status timeout')));c.on('error',reject);c.on('connect',()=>{const p=Buffer.alloc(2);p.writeUInt16BE(port);c.write(frame(Buffer.concat([variable(0),variable(-1),str('127.0.0.1'),p,variable(1)])));c.write(frame(variable(0)))});c.on('data',v=>{b=Buffer.concat([b,v]);let len=read(b);if(!len||b.length<len.bytes+len.value)return;const payload=b.subarray(len.bytes,len.bytes+len.value);const id=read(payload);if(id.value!==0){reject(Error('Unexpected status packet'));c.end();return}const s=read(payload,id.bytes);try{resolve(JSON.parse(payload.subarray(id.bytes+s.bytes,id.bytes+s.bytes+s.value).toString('utf8')))}catch(e){reject(e)}c.end()})})}
(async()=>{const record=JSON.parse(fs.readFileSync('server-minestom/run/world-infusion/owned-process.json','utf8').replace(/^\uFEFF/,''));const port=Number(record.Address.split(':')[1]);const info=await status(port);if(!/26\.2/.test(info.version.name))throw Error('Wrong Minecraft runtime');const log=fs.readFileSync(record.Log,'utf8');if(!log.includes('PROJECTS_WORLD_INFUSION_READY'))throw Error('Missing readiness');const match=log.match(/CORE_UI_PACK_READY url=(\S+)/);if(!match)throw Error('Pack server failed');const url=new URL(match[1]);if(url.hostname!=='127.0.0.1'||url.protocol!=='http:')throw Error('Non-local pack URL');const response=await fetch(url);if(!response.ok)throw Error('Pack HTTP '+response.status);const zip=await JSZip.loadAsync(Buffer.from(await response.arrayBuffer()),{checkCRC32:true});for(const name of ['matrix','pedestal','jar_ember','jar_tide','jar_gale']){const item=JSON.parse(await zip.file('assets/projects/items/infusion/'+name+'.json').async('string'));if(item.model.model!=='projects:infusion/'+name)throw Error('Model ref');const model=JSON.parse(await zip.file('assets/projects/models/infusion/'+name+'.json').async('string'));if(!model.elements.length)throw Error('Empty world model')};for(const n of ['stone','brass','glass','seal']){const m=await sharp(await zip.file('assets/projects/textures/infusion/'+n+'.png').async('nodebuffer')).metadata();if(m.width!==16||m.height!==16)throw Error('Wrong pixel master')}
const result={passed:true,testedAt:new Date().toISOString(),minecraft:info.version.name,protocol:info.version.protocol,localAddress:record.Address,serverPid:record.ProcessId,maxHeapMB:512,isolatedSave:record.SaveDirectory,resourcePackHTTP:true,resourcePackCRC:true,models:5,pixelMasters:4,clientGui:false,manualFeel:false};fs.writeFileSync('.tools/world-infusion-evidence/server-smoke.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));})().catch(e=>{console.error(e);process.exitCode=1});
