"""User-reviewable current contact only, before/after normal-size actual pixels."""
import json,copy,hashlib,numpy as np
from PIL import Image,ImageDraw,ImageFont
import noctveil_v42_pose_tools as p
import mesh_preview
env=p.prefix(p.ROOT/'work/probe_v44_contact_separation.py','rows');out=p.ROOT/'outputs/v44_contact_delivery';out.mkdir(exist_ok=True)
path=p.ROOT/'outputs/v44_contact_study/independent_membrane_flanks_03/projects_noctveil_v44_contact_flanks.bbmodel';current=json.loads(path.read_text());contact=next(a for a in current['animations'] if a['name']=='v44_contact_static');old=json.loads((p.ROOT/'outputs/v43_gesture_study/projects_noctveil_v43_three_pose_study.bbmodel').read_text());prior=next(a for a in old['animations'] if a['name']=='contact_pose_v43')
model=copy.deepcopy(p.rig.source);model['name']=model['model_identifier']='projects_noctveil_v44_contact_pose_study';model['animations']=[copy.deepcopy(contact)]+copy.deepcopy(p.rig.source['animations']);targetpath=out/(model['name']+'.bbmodel');targetpath.write_text(json.dumps(model,separators=(',',':'))+'\n',encoding='utf8')
assert all(model[k]==p.rig.source[k] for k in ['elements','outliner','textures']) and model['animations'][1:]==p.rig.source['animations']
board=Image.new('RGB',(1280,570),(31,28,35));ink=ImageDraw.Draw(board);font=ImageFont.truetype('C:/Windows/Fonts/segoeui.ttf',12);rows=[]
for j,view in enumerate(env['bounds']):
 for col,(label,c) in enumerate([('V43 / previous',prior),('V44 / current contact',contact)]):
  im=mesh_preview.render(env['env']['rd'],env['env']['atlas'],c,0,view,(320,240),env['bounds'][view]);x=col*320;y=30+j*270;board.paste(im,(x,y+25));ink.text((x+4,y+5),label+' / '+view+' / plain',font=font,fill='white')
  guided=im.copy();d=ImageDraw.Draw(guided);pts=env['screen'](env['target'],view)
  for a in range(8):
   for b in range(a+1,8):
    if np.count_nonzero(env['target'][a]!=env['target'][b])==1:d.line([tuple(pts[a]),tuple(pts[b])],fill=(113,130,151),width=1)
  x=(col+2)*320;board.paste(guided,(x,y+25));ink.text((x+4,y+5),label+' / fixed guide',font=font,fill='white')
ink.text((8,5),'ACTUAL CONTACT POSE COMPARISON / each card320x240 / same camera / original pixels / not art-passed',font=font,fill='white');png=out/'noctveil_v44_contact_pose_comparison.png';board.save(png)
audit=p.prefix(p.ROOT/'work/inspect_v42_self_collision.py','start');audit['model']=model;body=audit['audit'](contact,0);baseline=json.loads((p.ROOT/'outputs/v42_path_study/iteration_05/v42_self_surface_crossing_audit.json').read_text())['baselines'];pairs={tuple(sorted((h['a'],h['b']))) for r in baseline for h in r['crossings']}
newpairs=[h for h in body['crossings'] if h['attacking_wing_involved'] and not h['directly_adjacent_bones'] and tuple(sorted((h['a'],h['b']))) not in pairs]
result={'model':str(targetpath.relative_to(p.ROOT)),'sha256':hashlib.sha256(targetpath.read_bytes()).hexdigest(),'comparison':str(png.relative_to(p.ROOT)),'source_geometry_hierarchy_uv_textures_original3_clips_exact':True,'actual_change':'Wrist from[4.9275,19.6478,-26.4979] to[8,18,-27.5]; shoulder roll270->315 puts elbow outside shoulder in both projections. Neck[10,4.8,0]->[0,-35,0] separates cheek from route. Existing right_folded_membrane rotates nativeZ-25 independently of physical forearm; original outer crease branch retained. Same fixed opponent guide. No changed vertex, hierarchy, texture, UV or source clips.','primary_cause':'Previous controller omitted independent membrane bone and effectively moved three leading membrane panels with forearm. Existing rig supports separate membrane rotation; no shape redesign or additional bone needed for this contact pose.','current_contact_quality':'The hand/claws are separated from the cheek in plain320x240 views, and existing two hooks visibly reach the fixed guide front/right edge. Still no whole-gesture artistic acceptance.','largest_remaining_obstacle':'At opposite-side exit the hand still becomes hidden in oblique view; complete outside->inside->opposite-side interpolation and recovery to closed idle are not established.','full_body_surface_check':body,'new_nonadjacent_wing_crossings':newpairs,'full_body_surface_limits':'All128 meshes at one actual static pose only; noncoplanar proper triangle crossings. Baseline presence is not harmlessness. Coplanar overlap, containment and all continuous/interpolated motion unproved.','rejected_outer_fold':'Alternate outer crease branch improved visibility but introduced26 new nonadjacent wing crossing pairs; rejected, not used in delivered model.','pose_only':True,'native_current_verified':False,'software_shading_differs_from_native':True,'whole_body_gesture_pass':False,'full_body_pass':False,'art_pass':False,'game_connected':False,'gui_used':False,'minecraft_windows_or_input_touched':False}
(out/'v44_contact_pose_evidence.json').write_text(json.dumps(result,indent=2)+'\n',encoding='utf8');print(json.dumps({'sha256':result['sha256'],'new_wing_pairs':[(h['a'],h['b'],h['segment_length']) for h in newpairs]}),flush=True)
