import json,hashlib
from pathlib import Path
root=Path(__file__).resolve().parents[1];out=root/'outputs/v44_contact_delivery';e=json.loads((out/'v44_contact_pose_evidence.json').read_text());lib=json.loads((root/'work/PARENT_HANDOFF_V44_CONTACT_LIBRARY.json').read_text())
assert hashlib.sha256((root/'outputs/v32/projects_noctveil_v32_idle_storage.bbmodel').read_bytes()).hexdigest()=='c0f243de33b471e201052dc6fb66d4372356e56aa645f669ce97ce4016aa0878'
assert hashlib.sha256((root/'outputs/v43_gesture_study/projects_noctveil_v43_three_pose_study.bbmodel').read_bytes()).hexdigest()=='6f1e5458bf90b37e46891bb02e51646c3a759bbf0e82200a157b1c75f8beb2f4'
handoff={'current_reviewable_candidate':e['model'],'model_sha256':e['sha256'],'comparison_library':lib,'what_changed_visually':e['actual_change'],'root_cause':e['primary_cause'],'largest_remaining_obstacle':e['largest_remaining_obstacle'],'scope':'Current one contact pose only; previous V43+V42 copies preserved. Native07 is not evidence for currentV44. Concept->real3Dmodel->partial static visual/surface QA->game not connected.','finite_contact_notes':'Existing two hooks intersect fixed target at front/right edge; palm/radius and membrane do not intersect target. Head/crown crossings0, minimum groundY+.003. No all-time collision proof. New unrelated/adjacent wing crossing pairs remain in evidence; segment length is not penetration depth.','new_contact_surface_pairs':[(h['a'],h['b'],h['segment_length']) for h in e['new_nonadjacent_wing_crossings']],'source_geometry_hierarchy_uv_textures_original3_clips_exact':True,'geometry_redesign_needed':False,'native_current_verified':False,'full_body_pass':False,'whole_body_gesture_pass':False,'art_pass':False,'game_connected':False,'gui_used':False,'minecraft_input_touched':False,'next_authorized_work':'Expose hand past opposite shoulder in oblique view using existing membrane control; rebuild real connected arm/chest arc and idle recovery. Source changes not currently necessary or authorized. Rejected outer-fold knot not reused.','push_executor':'Parent task01a1022f-884a-7190-92a6-e08bb1289093; this worker has no Git repo/branch/commit and does not push. Previous v42/v43 delivery manifests remain unchanged.'}
(root/'work/PARENT_HANDOFF_V44_CONTACT_RESEARCH.json').write_text(json.dumps(handoff,indent=2)+'\n',encoding='utf8')
paths=[out/'projects_noctveil_v44_contact_pose_study.bbmodel',out/'noctveil_v44_contact_pose_comparison.png',out/'v44_contact_pose_evidence.json']+[root/'work'/n for n in ['noctveil_v44_pose_tools.py','probe_v44_contact_separation.py','build_v44_readable_flanks_03.py','save_v44_contact_delivery.py','save_v44_contact_checkpoint.py']]
manifest={'workspace':str(root),'is_git_repository':False,'branch':None,'commit':None,'push_executor':handoff['push_executor'],'files':[{'local_path':str(p),'workspace_relative_path':p.relative_to(root).as_posix(),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in paths],'exclusions':'Reference originals, runtimes/profiles/Library metadata and helpers, trial outputs and superseded candidates. Authoring sources depend on existing Noctveil workspace helpers; delivered bbmodel self-contained.'}
(root/'work/PARENT_HANDOFF_V44_PUSH_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf8');print(json.dumps({'model':e['model'],'sha256':e['sha256'],'comparison_library':lib['library_file_id'],'manifest_files':len(paths)}))
